In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [2]:
data = {
    'CGPA': [9.2, 8.0, 8.5, 6.0, 6.5, 8.2, 5.8, 8.9],
    'Assessment': [85, 80, 81, 45, 50, 72, 38, 91],
    'Project': [8, 7, 8, 5, 4, 7, 5, 9],
    'Result': ['Pass', 'Pass', 'Pass', 'Fail', 'Fail', 'Pass', 'Fail', 'Pass']
}

dataset = pd.DataFrame(data)

print("Dataset:")
print(dataset)

Dataset:
   CGPA  Assessment  Project Result
0   9.2          85        8   Pass
1   8.0          80        7   Pass
2   8.5          81        8   Pass
3   6.0          45        5   Fail
4   6.5          50        4   Fail
5   8.2          72        7   Pass
6   5.8          38        5   Fail
7   8.9          91        9   Pass


In [3]:
print("Shape of dataset:", dataset.shape)

print("\nFirst 5 records:")
print(dataset.head())

print("\nLast 2 records:")
print(dataset.tail(2))

Shape of dataset: (8, 4)

First 5 records:
   CGPA  Assessment  Project Result
0   9.2          85        8   Pass
1   8.0          80        7   Pass
2   8.5          81        8   Pass
3   6.0          45        5   Fail
4   6.5          50        4   Fail

Last 2 records:
   CGPA  Assessment  Project Result
6   5.8          38        5   Fail
7   8.9          91        9   Pass


In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print("Input features:")
print(X)

print("\nOutput labels:")
print(y)

Input features:
[[ 9.2 85.   8. ]
 [ 8.  80.   7. ]
 [ 8.5 81.   8. ]
 [ 6.  45.   5. ]
 [ 6.5 50.   4. ]
 [ 8.2 72.   7. ]
 [ 5.8 38.   5. ]
 [ 8.9 91.   9. ]]

Output labels:
['Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Fail' 'Pass']


In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Training data:")
print(X_train)

print("\nTesting data:")
print(X_test)

Training data:
[[ 1.21445715  0.94526291  0.79240582]
 [ 1.00222192  1.22884178  1.32067636]
 [ 0.71924161  0.75621033  0.79240582]
 [-0.69565992 -0.70894718 -1.32067636]
 [-1.0493853  -0.94526291 -0.79240582]
 [-1.19087545 -1.27610493 -0.79240582]]

Testing data:
[[0.36551623 0.70894718 0.26413527]
 [0.50700638 0.33084202 0.26413527]]


In [7]:
classifier = KNeighborsClassifier(n_neighbors=3)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("Actual values:   ", y_test)
print("Predicted values:", y_pred)

Actual values:    ['Pass' 'Pass']
Predicted values: ['Pass' 'Pass']


In [8]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[2]]

Classification Report:
              precision    recall  f1-score   support

        Pass       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


In [10]:
new_student = [[9.1, 85, 8]]

new_student_scaled = scaler.transform(new_student)

prediction = classifier.predict(new_student_scaled)

print("New Student:", new_student)
print("Predicted Result:", prediction[0])

New Student: [[9.1, 85, 8]]
Predicted Result: Pass


In [12]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

data = {
    'CGPA': [9.2, 8.0, 8.5, 6.0, 6.5, 8.2, 5.8, 8.9],
    'Assessment': [85, 80, 81, 45, 50, 72, 38, 91],
    'Project': [8, 7, 8, 5, 4, 7, 5, 9],
    'Result': ['Pass', 'Pass', 'Pass', 'Fail', 'Fail', 'Pass', 'Fail', 'Pass']
}

dataset = pd.DataFrame(data)

print(dataset.shape)
print(dataset.head())
print(dataset.tail(2))

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print("\nInput:")
print(X)

print("\nOutput:")
print(y)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

classifier = KNeighborsClassifier(n_neighbors=3)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

new_student = [[9.1, 85, 8]]
new_student_scaled = scaler.transform(new_student)

prediction = classifier.predict(new_student_scaled)

print("New Student:", new_student)
print("Predicted Result:", prediction[0])

(8, 4)
   CGPA  Assessment  Project Result
0   9.2          85        8   Pass
1   8.0          80        7   Pass
2   8.5          81        8   Pass
3   6.0          45        5   Fail
4   6.5          50        4   Fail
   CGPA  Assessment  Project Result
6   5.8          38        5   Fail
7   8.9          91        9   Pass

Input:
[[ 9.2 85.   8. ]
 [ 8.  80.   7. ]
 [ 8.5 81.   8. ]
 [ 6.  45.   5. ]
 [ 6.5 50.   4. ]
 [ 8.2 72.   7. ]
 [ 5.8 38.   5. ]
 [ 8.9 91.   9. ]]

Output:
['Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Fail' 'Pass']

Confusion Matrix:
[[2]]

Classification Report:
              precision    recall  f1-score   support

        Pass       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

New Student: [[9.1, 85, 8]]
Predicted Result: Pass


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:409: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


In [13]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

data = {
    'CGPA': [9.2, 8.0, 8.5, 6.0, 6.5, 8.2, 5.8, 8.9],
    'Assessment': [85, 80, 81, 45, 50, 72, 38, 91],
    'Project': [8, 7, 8, 5, 4, 7, 5, 9],
    'Result': ['Pass', 'Pass', 'Pass', 'Fail', 'Fail', 'Pass', 'Fail', 'Pass']
}

dataset = pd.DataFrame(data)

print(dataset.shape)
print(dataset.head())
print(dataset.tail(2))

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print("\nInput:")
print(X)

print("\nOutput:")
print(y)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

classifier = KNeighborsClassifier(n_neighbors=3)

classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

new_student = [[9.1, 85, 8]]
new_student_scaled = scaler.transform(new_student)

prediction = classifier.predict(new_student_scaled)

print("New Student:", new_student)
print("Predicted Result:", prediction[0])

(8, 4)
   CGPA  Assessment  Project Result
0   9.2          85        8   Pass
1   8.0          80        7   Pass
2   8.5          81        8   Pass
3   6.0          45        5   Fail
4   6.5          50        4   Fail
   CGPA  Assessment  Project Result
6   5.8          38        5   Fail
7   8.9          91        9   Pass

Input:
[[ 9.2 85.   8. ]
 [ 8.  80.   7. ]
 [ 8.5 81.   8. ]
 [ 6.  45.   5. ]
 [ 6.5 50.   4. ]
 [ 8.2 72.   7. ]
 [ 5.8 38.   5. ]
 [ 8.9 91.   9. ]]

Output:
['Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass' 'Fail' 'Pass']

Confusion Matrix:
[[1 0]
 [0 1]]

Classification Report:
              precision    recall  f1-score   support

        Fail       1.00      1.00      1.00         1
        Pass       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2

New Student: [[9.1, 85, 8]]
Predicted Result: Pass
