In [1]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# Derivative of sigmoid
def sigmoid_derivative(x):
    return x * (1 - x)


# XOR input
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Expected output
expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
])

# Learning rate
lr = 0.5

# Number of neurons
inputLayerNeurons = 2
hiddenLayerNeurons = 4
outputLayerNeurons = 1

# Initial weights
hidden_weights = np.array([
    [0.5, 0.4, 0.3, 0.2],
    [0.5, 0.4, 0.3, 0.2]
])

output_weights = np.array([
    [0.4],
    [0.3],
    [0.2],
    [0.1]
])

# Biases
hidden_bias = np.zeros((1, hiddenLayerNeurons))
output_bias = np.zeros((1, outputLayerNeurons))

# Training
for epoch in range(10000):

    # -------------------------------
    # FORWARD PROPAGATION
    # -------------------------------

    hidden_layer_activation = np.dot(inputs, hidden_weights)
    hidden_layer_activation += hidden_bias

    hidden_layer_output = sigmoid(hidden_layer_activation)

    output_layer_activation = np.dot(
        hidden_layer_output,
        output_weights
    )
    output_layer_activation += output_bias

    predicted_output = sigmoid(output_layer_activation)

    # -------------------------------
    # BACKPROPAGATION
    # -------------------------------

    error = expected_output - predicted_output

    d_predicted_output = (
        error * sigmoid_derivative(predicted_output)
    )

    error_hidden_layer = np.dot(
        d_predicted_output,
        output_weights.T
    )

    d_hidden_layer = (
        error_hidden_layer *
        sigmoid_derivative(hidden_layer_output)
    )

    # Update output weights
    output_weights += (
        np.dot(hidden_layer_output.T, d_predicted_output)
        * lr
    )

    # Update output bias
    output_bias += (
        np.sum(d_predicted_output, axis=0, keepdims=True)
        * lr
    )

    # Update hidden weights
    hidden_weights += (
        np.dot(inputs.T, d_hidden_layer)
        * lr
    )

    # Update hidden bias
    hidden_bias += (
        np.sum(d_hidden_layer, axis=0, keepdims=True)
        * lr
    )


# -------------------------------
# FINAL OUTPUT
# -------------------------------

print("Final Hidden Weights:")
print(hidden_weights)

print("\nFinal Hidden Bias:")
print(hidden_bias)

print("\nFinal Output Weights:")
print(output_weights)

print("\nFinal Output Bias:")
print(output_bias)

print("\nOutput from Neural Network:")
print(predicted_output)

print("\nBinary Output:")
print((predicted_output >= 0.5).astype(int))

print("\nExpected Output:")
print(expected_output)

Final Hidden Weights:
[[6.8371101  2.1359696  2.71879717 2.7681595 ]
 [6.8371101  2.1359696  2.71879717 2.7681595 ]]

Final Hidden Bias:
[[-3.17273585 -3.51862009 -4.38080037 -4.45319451]]

Final Output Weights:
[[11.1970874 ]
 [-4.52477427]
 [-5.47451319]
 [-5.57881546]]

Final Output Bias:
[[-4.09739899]]

Output from Neural Network:
[[0.01966058]
 [0.98473007]
 [0.98473007]
 [0.01466794]]

Binary Output:
[[0]
 [1]
 [1]
 [0]]

Expected Output:
[[0]
 [1]
 [1]
 [0]]
