In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    return x * (1 - x)

def checkError(predicted_output):
    expected_output = np.array([
        [0],
        [1],
        [1],
        [0]
    ])

    for i, j in zip(expected_output, predicted_output):
        if abs(i[0] - j[0]) > 0.001:
            return True

    return False

inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
], dtype=float)


expected_output = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=float)

inputLayerNeurons = int(input("Enter no of input layer: "))
hiddenLayerNeurons = int(input("Enter no of hidden layer: "))
outputLayerNeurons = int(input("Enter no of output layer: "))

hidden_weights = []

for i in range(1, inputLayerNeurons + 1):

    temp = []

    for j in range(
        inputLayerNeurons + 1,
        inputLayerNeurons + hiddenLayerNeurons + 1
    ):

        temp.append(
            float(input("w" + str(i) + str(j) + ": "))
        )

    hidden_weights.append(temp)

output_weights = []

for i in range(
    inputLayerNeurons + 1,
    inputLayerNeurons + hiddenLayerNeurons + 1
):

    temp = []

    for j in range(
        inputLayerNeurons + hiddenLayerNeurons + 1,
        inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1
    ):

        temp.append(
            float(input("w" + str(i) + str(j) + ": "))
        )

    output_weights.append(temp)


hidden_bias = []
output_bias = []

for i in range(
    inputLayerNeurons + 1,
    inputLayerNeurons + hiddenLayerNeurons + outputLayerNeurons + 1
):

    if i > inputLayerNeurons + hiddenLayerNeurons:

        output_bias.append(
            float(input("o" + str(i) + ": "))
        )

    else:

        hidden_bias.append(
            float(input("o" + str(i) + ": "))
        )

hidden_weights = np.asarray(hidden_weights, dtype=float)
hidden_bias = np.asarray([hidden_bias], dtype=float)

output_weights = np.asarray(output_weights, dtype=float)
output_bias = np.asarray([output_bias], dtype=float)


print("\nInitial hidden weights:")
print(hidden_weights)

print("\nInitial hidden biases:")
print(hidden_bias)

print("\nInitial output weights:")
print(output_weights)

print("\nInitial output biases:")
print(output_bias)


epoch = 0
lr = 0.1
max_epochs = 100000

predicted_output = np.zeros((4, 1))


while checkError(predicted_output) and epoch < max_epochs:

    epoch += 1

 

    hidden_layer_activation = np.dot(
        inputs,
        hidden_weights
    )

    hidden_layer_activation += hidden_bias

    hidden_layer_output = sigmoid(
        hidden_layer_activation
    )

    output_layer_activation = np.dot(
        hidden_layer_output,
        output_weights
    )

    output_layer_activation += output_bias

    predicted_output = sigmoid(
        output_layer_activation
    )



    error = expected_output - predicted_output

    d_predicted_output = (
        error *
        sigmoid_derivative(predicted_output)
    )

    error_hidden_layer = d_predicted_output.dot(
        output_weights.T
    )

    d_hidden_layer = (
        error_hidden_layer *
        sigmoid_derivative(hidden_layer_output)
    )


    output_weights += (
        hidden_layer_output.T.dot(
            d_predicted_output
        ) * lr
    )

    output_bias += (
        np.sum(
            d_predicted_output,
            axis=0,
            keepdims=True
        ) * lr
    )

    hidden_weights += (
        inputs.T.dot(
            d_hidden_layer
        ) * lr
    )

    hidden_bias += (
        np.sum(
            d_hidden_layer,
            axis=0,
            keepdims=True
        ) * lr
    )


print("\nInitial training completed")
print("Epochs:", epoch)

print("\nFine-Tuning Started")

fine_tune_lr = 0.01
fine_tune_epochs = 1000


for i in range(fine_tune_epochs):


    hidden_layer_activation = np.dot(
        inputs,
        hidden_weights
    )

    hidden_layer_activation += hidden_bias

    hidden_layer_output = sigmoid(
        hidden_layer_activation
    )

    output_layer_activation = np.dot(
        hidden_layer_output,
        output_weights
    )

    output_layer_activation += output_bias

    predicted_output = sigmoid(
        output_layer_activation
    )


    error = expected_output - predicted_output

    d_predicted_output = (
        error *
        sigmoid_derivative(predicted_output)
    )

    error_hidden_layer = d_predicted_output.dot(
        output_weights.T
    )

    d_hidden_layer = (
        error_hidden_layer *
        sigmoid_derivative(hidden_layer_output)
    )


    output_weights += (
        hidden_layer_output.T.dot(
            d_predicted_output
        ) * fine_tune_lr
    )

    output_bias += (
        np.sum(
            d_predicted_output,
            axis=0,
            keepdims=True
        ) * fine_tune_lr
    )


    hidden_weights += (
        inputs.T.dot(
            d_hidden_layer
        ) * fine_tune_lr
    )

    hidden_bias += (
        np.sum(
            d_hidden_layer,
            axis=0,
            keepdims=True
        ) * fine_tune_lr
    )


print("Fine-Tuning Completed")

print("\nFinal hidden weights:")
print(hidden_weights)

print("\nFinal hidden bias:")
print(hidden_bias)

print("\nFinal output weights:")
print(output_weights)

print("\nFinal output bias:")
print(output_bias)

print("\nOutput from neural network:")

for value in predicted_output:
    print(round(float(value[0]), 3))


print("\nExpected output:")
print("0 1 1 0")

print("\nTotal fine-tuning epochs:")
print(fine_tune_epochs)

Enter no of input layer:  2
Enter no of hidden layer:  2
Enter no of output layer:  1
w13:  -0.2
w14:  0.4
w23:  0.2
w24:  -0.3
w35:  0.2
w45:  -0.3
o3:  0
o4:  0
o5:  0



Initial hidden weights:
[[-0.2  0.4]
 [ 0.2 -0.3]]

Initial hidden biases:
[[0. 0.]]

Initial output weights:
[[ 0.2]
 [-0.3]]

Initial output biases:
[[0.]]

Initial training completed
Epochs: 100000

Fine-Tuning Started
Fine-Tuning Completed

Final hidden weights:
[[ 5.75567611  6.62246378]
 [-5.97275776 -6.5341183 ]]

Final hidden bias:
[[-3.0922607   3.31523881]]

Final output weights:
[[10.34749031]
 [-9.8628158 ]]

Final output bias:
[[4.65526794]]

Output from neural network:
0.012
0.986
0.989
0.011

Expected output:
0 1 1 0

Total fine-tuning epochs:
1000
